[package]
name = "bevy-experiment"
version = "0.1.0"
authors = ["Jerred Shepherd <ShepherdJerred@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.4"
bevy_tiled_prototype = "0.1.0"
cargo-edit-locally = "0.1.3"

[replace]
'bevy_tiled_prototype:0.1.0' = { path = 'bevy_tiled' }
