name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libasound2-dev libudev
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Clone bevy-tield
      run: git clone https://github.com/framp/bevy_tiled
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: target/
    - uses: eine/tip@master
      with:
        tag: continous-integration
        token: ${{ secrets.ACCESS_TOKEN }}
        files: |
          target/
